before_install:
- sudo apt-get update -qq
- sudo apt-get install texlive-latex-base
script:
- mkdir build
- pdflatex -output-directory build test.tex
deploy:
  provider: releases
  api_key:
    secure:
  file:
    - build/root.pdf
  skip_cleanup: true
  on:
    all_branches: true
